-- JTea's free simulator pack supplies the authored maps, shops, foliage and rocks.
local Config=require(game.ReplicatedStorage.Modules.GameConfig)
local MapBuilder={}
local V=Vector3.new local C=Color3.fromRGB
local function part(parent,name,size,pos,color,material)
 local p=Instance.new('Part') p.Name=name p.Size=size p.Position=pos p.Color=color
 p.Material=material or Enum.Material.SmoothPlastic p.Anchored=true p.TopSurface=Enum.SurfaceType.Smooth p.Parent=parent return p
end
local function label(p,text)
 local gui=Instance.new('BillboardGui') gui.Size=UDim2.fromOffset(210,56) gui.StudsOffset=V(0,5,0) gui.MaxDistance=95 gui.Parent=p
 local t=Instance.new('TextLabel') t.Size=UDim2.fromScale(1,1) t.BackgroundTransparency=1 t.Text=text
 t.Font=Enum.Font.FredokaOne t.TextScaled=true t.TextColor3=C(255,255,255) t.TextStrokeColor3=C(25,44,62) t.TextStrokeTransparency=0 t.Parent=gui
end
local function place(template,parent,name,pos,height)
 local m=template:Clone() m.Name=name m.Parent=parent
 if height then local _,size=m:GetBoundingBox() m:ScaleTo(m:GetScale()*height/size.Y) end
 local cf,size=m:GetBoundingBox()
 m:PivotTo(CFrame.new(pos+V(0,size.Y/2,0))*cf:Inverse()*m:GetPivot())
 for _,d in ipairs(m:GetDescendants()) do
  if d:IsA('BasePart') then d.Anchored=true
  elseif d:IsA('LuaSourceContainer') then d:Destroy() end
 end
 return m
end
function MapBuilder.Build()
 local pack=game.ServerStorage:FindFirstChild('JTeaSimulatorPack')
 assert(pack,'Import the free JTea pack 7151365600 into ServerStorage as JTeaSimulatorPack (see ASSETS.md).')
 local library=pack:GetChildren()[1]:GetChildren()[1]
 local old=workspace:FindFirstChild('Map') if old then old:Destroy() end
 local preview=workspace:FindFirstChild('JTeaPreview') if preview then preview:Destroy() end
 local map=Instance.new('Folder') map.Name='Map' map.Parent=workspace
 local zones=Instance.new('Folder') zones.Name='Zones' zones.Parent=map
 local interactive=Instance.new('Folder') interactive.Name='Interactives' interactive.Parent=map
 local function biome(name,z,floorName)
  local m=library[name].Map:GetChildren()[1]:Clone() m.Name=name m.Parent=zones
  local floor=m:FindFirstChild(floorName)
  assert(floor,'Pack floor missing for '..name)
  local offset=V(-floor.Position.X,1-(floor.Position.Y+floor.Size.Y/2),z-floor.Position.Z)
  m:PivotTo(m:GetPivot()+offset)
  for _,d in ipairs(m:GetDescendants()) do
   if d:IsA('BasePart') then
    d.Anchored=true
    if d:IsA('MeshPart') and d.Material==Enum.Material.SmoothPlastic then
     d.Material=d.Color.G>d.Color.R*1.15 and Enum.Material.Grass or Enum.Material.Slate
    end
   end
  end
  return m
 end
 biome('Forest',0,'Texture Part') biome('Ice',-310,'Floor')
 -- Replace only terrain previously generated by this project, then sculpt beneath the authored floors:
 -- a ground slab just under floor height plus low hills along both sides to close in each zone.
 local terrain=workspace.Terrain
 for _,zone in ipairs({{z=0,surface=Enum.Material.Grass},{z=-310,surface=Enum.Material.Snow}}) do
  terrain:FillBlock(CFrame.new(0,-8,zone.z),V(280,24,280),Enum.Material.Air)
  terrain:FillBlock(CFrame.new(0,-8,zone.z),V(258,16,258),zone.surface)
  for _,side in ipairs({-1,1}) do for i=1,5 do
   terrain:FillBall(V(side*122,-3,zone.z-95+i*36),12,zone.surface)
  end end
 end
 require(script.Parent.AssetScenery).Build(map)
 local templateSpawn=workspace:FindFirstChild('SpawnLocation') if templateSpawn then templateSpawn.Enabled=false end
 local spawn=Instance.new('SpawnLocation') spawn.Name='MainSpawn' spawn.Size=V(10,0.5,10)
 spawn.Position=V(0,1.3,40) spawn.Transparency=1 spawn.Anchored=true spawn.Neutral=true spawn.Duration=0 spawn.Parent=map
 local function pad(name,pos,color)
  local p=part(interactive,name,V(10,0.6,10),pos,color,Enum.Material.Neon) return p
 end
 pad('SpawnRing',V(0,1.2,40),C(68,219,238))
 local orb=part(interactive,'ClickOrb',V(5,5,5),V(0,5,10),C(255,212,94),Enum.Material.Neon) orb.Shape=Enum.PartType.Ball
 label(orb,'CLICK TO EARN')
 local altar=pad('RebirthAltar',V(49,1.5,0),C(177,104,240)) label(altar,'REBIRTH\nPermanent power')
 place(library.Forest['Extra Portal']:GetChildren()[1],zones,'RebirthShrine',V(49,1,0),18)
 local eggs={}
 for _,egg in ipairs(Config.Eggs) do
  local late=egg.Zone=='Frost' local pos=late and V(-35,1,-305) or V(-42,1,-3)
  place(library[late and 'Ice' or 'Forest'].Shop:GetChildren()[1],zones,egg.Id..'Shop',pos,16)
  local p=part(interactive,egg.Id,V(4.5,6,4.5),pos+V(0,4.5,5),late and C(255,216,99) or C(92,233,236),Enum.Material.Neon)
  p.Shape=Enum.PartType.Ball label(p,egg.Name..'\n'..egg.Cost..' coins') eggs[egg.Id]=p
 end
 place(library.Ice['Extra Portal']:GetChildren()[1],zones,'IcePortal',V(0,1,-63),19)
 local door=part(interactive,'FrostPortal',V(10,12,2),V(0,7,-61),C(90,206,255),Enum.Material.Neon)
 door.Transparency=0.65 door.CanCollide=false door:SetAttribute('Destination',V(0,5,-270))
 label(door,'FROST WORLD\n'..Config.FrostZoneRequiredRebirths..' rebirth required')
 local back=pad('ReturnPortal',V(0,1.4,-260),C(84,230,186)) label(back,'RETURN TO FOREST')
 local prompt=Instance.new('ProximityPrompt') prompt.ActionText='Return' prompt.ObjectText='Forest' prompt.HoldDuration=0 prompt.Parent=back
 prompt.Triggered:Connect(function(player) if player.Character then player.Character:PivotTo(CFrame.new(0,5,40)) end end)
 local lighting=game:GetService('Lighting') lighting.ClockTime=14 lighting.Brightness=2
 lighting.Ambient=C(128,141,166) lighting.OutdoorAmbient=C(161,178,192)
 local grade=lighting:FindFirstChild('SimulatorGrade') or Instance.new('ColorCorrectionEffect')
 grade.Name='SimulatorGrade' grade.Saturation=0.08 grade.Contrast=0.07 grade.Parent=lighting
 local bloom=lighting:FindFirstChild('SimulatorBloom') or Instance.new('BloomEffect')
 bloom.Name='SimulatorBloom' bloom.Intensity=0.22 bloom.Size=18 bloom.Threshold=1.5 bloom.Parent=lighting
 return {ClickOrb=orb,RebirthAltar=altar,EggParts=eggs,FrostPortal=door}
end
return MapBuilder
