"""Generates src/ReplicatedStorage/Modules/ArtMaterials.lua from the art package's FBX files.

Open Cloud imports every mesh with the shared palette-atlas texture. Almost every piece uses a single
Blender material, so the game swaps the texture for a flat Color (and Neon for glowing materials),
which reads cleaner than a sampled atlas. Pieces with several materials keep the texture.

  python3 tools/art/gen_materials.py
"""
import json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
import fbxread

ROOT = Path(__file__).resolve().parents[2]
EXPORTS = ROOT / 'art' / 'exports'
OUT = ROOT / 'src' / 'ReplicatedStorage' / 'Modules' / 'ArtMaterials.lua'
NEON_AT = 0.25  # Blender emission strength from which a material renders as Neon

def srgb(c):
    return round(255 * (12.92 * c if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055))

def main():
    manifest = json.loads((EXPORTS / 'manifest.json').read_text())
    files = ['World_Assembled'] + [m['file'][:-4] for m in manifest if m['file'].startswith(('Pet_', 'Props_', 'Variant_'))]
    palette, models = {}, {}
    for stem in files:
        data = fbxread.load(EXPORTS / (stem + '.fbx'))
        for name, color, glow in data['materials'].values():
            palette[name] = ([srgb(c) for c in color], glow >= NEON_AT)
        parts = {}
        for mesh in data['meshes']:
            used = {t[6] for t in mesh['tris']}
            if len(used) == 1 and None not in used:
                parts[mesh['name']] = used.pop()
        models[stem] = parts
    lines = ['-- Generated by tools/art/gen_materials.py from the art package; do not edit by hand.',
             '-- Palette: material -> {r, g, b, neon}. Models: imported model name -> {piece -> material}.',
             '-- Pieces not listed use several materials and keep the imported atlas texture.',
             'return {', '\tPalette = {']
    for name, (rgb, neon) in sorted(palette.items()):
        lines.append(f'\t\t{name} = {{ {rgb[0]}, {rgb[1]}, {rgb[2]}, {str(neon).lower()} }},')
    lines += ['\t},', '\tModels = {']
    for stem in files:
        lines.append(f'\t\t{stem} = {{')
        for part, mat in sorted(models[stem].items()):
            lines.append(f'\t\t\t[{json.dumps(part)}] = "{mat}",')
        lines.append('\t\t},')
    lines += ['\t},', '}', '']
    OUT.write_text('\n'.join(lines))
    print(OUT, sum(len(p) for p in models.values()), 'pieces', len(palette), 'materials')

if __name__ == '__main__':
    main()
